'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';

type LogEntry = { time: string; tone?: 'ok' | 'warn'; text: string };
type World = { position: { x: number; y: number; z: number }; health: number; food: number; yaw: number; dimension: string; players: string[]; blocks: string[][]; inventory?: ({ slot: number; name: string; displayName: string; count: number } | null)[] };
type View = 'console' | 'world' | 'security' | 'account';
type ConnectionMode = 'proxy' | 'railway-direct';
const initialLogs: LogEntry[] = [{ time: '21:03:18', tone: 'ok', text: 'Proxy-Guard aktiv · Direktverbindungen blockiert' }, { time: '21:03:19', text: 'Externer Worker ist bereit' }];

function blockKind(name: string) {
  if (/water|ice/.test(name)) return 'water'; if (/lava|fire/.test(name)) return 'lava'; if (/grass|leaves|moss|vine|fern/.test(name)) return 'grass';
  if (/sand|gravel|terracotta/.test(name)) return 'sand'; if (/wood|log|planks/.test(name)) return 'wood'; if (/snow/.test(name)) return 'snow';
  if (/stone|ore|deepslate|brick/.test(name)) return 'stone'; return name === 'unknown' ? 'unknown' : 'earth';
}

export default function Home() {
  const [status, setStatus] = useState('offline'); const [logs, setLogs] = useState<LogEntry[]>(initialLogs); const [world, setWorld] = useState<World | null>(null); const [connectionMode, setConnectionMode] = useState<ConnectionMode>('proxy'); const [railwayDirectAvailable, setRailwayDirectAvailable] = useState(false);
  const [view, setView] = useState<View>('console'); const [command, setCommand] = useState(''); const [busy, setBusy] = useState(false); const [liveStream, setLiveStream] = useState(false); const [viewerUrl, setViewerUrl] = useState('');
  const connected = ['online', 'connecting', 'disconnecting'].includes(status); const now = () => new Date().toLocaleTimeString('de-DE', { hour12: false });
  const heading = useMemo(() => ({ console: 'Command Center', world: 'Live-Welt', security: 'Sicherheit', account: 'Microsoft-Session' }[view]), [view]);
  const microsoftAuth = useMemo(() => {
    for (const entry of [...logs].reverse()) {
      const match = entry.text.match(/Microsoft-Gerätecode:\s*([A-Z0-9-]+)\s*·\s*(https?:\/\/\S+)/i);
      if (match) return { code: match[1], url: match[2] };
    }
    return null;
  }, [logs]);

  useEffect(() => { let active = true; type Payload = { status?: string; logs?: LogEntry[]; world?: World | null; connectionMode?: ConnectionMode; railwayDirectAvailable?: boolean }; const apply = (result: Payload) => { if (!active) return; setStatus(result.status ?? 'offline'); setWorld(result.world ?? null); if (result.connectionMode) setConnectionMode(result.connectionMode); setRailwayDirectAvailable(Boolean(result.railwayDirectAvailable)); if (result.logs?.length) setLogs(result.logs.map((entry) => ({ ...entry, time: new Date(entry.time).toLocaleTimeString('de-DE', { hour12: false }) }))); }; async function refresh() { try { const response = await fetch('/api/worker', { cache: 'no-store' }); if (response.ok) apply(await response.json() as Payload); } catch { /* stream reconnect and fallback handle this */ } } void refresh(); const events = new EventSource('/api/worker?action=events'); events.onopen = () => setLiveStream(true); events.onmessage = (event) => { try { apply(JSON.parse(event.data) as Payload); } catch { /* malformed frames are ignored */ } }; events.onerror = () => setLiveStream(false); const fallback = window.setInterval(() => { if (events.readyState !== EventSource.OPEN) void refresh(); }, 3000); return () => { active = false; events.close(); window.clearInterval(fallback); }; }, []);
  useEffect(() => { let active = true; if (view !== 'world' || status !== 'online') { setViewerUrl(''); return; } void fetch('/api/worker?action=viewer-ticket', { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{}' }).then(async (response) => { const result = await response.json() as { url?: string }; if (active && response.ok && result.url) setViewerUrl(result.url); }).catch(() => undefined); return () => { active = false; }; }, [view, status]);
  async function call(action: string, payload: object = {}) { const response = await fetch(`/api/worker?action=${action}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error ?? 'Aktion fehlgeschlagen'); }
  async function toggleConnection() { if (busy) return; setBusy(true); try { await call(connected ? 'disconnect' : 'connect'); setStatus(connected ? 'disconnecting' : 'connecting'); setLogs((items) => [...items, { time: now(), tone: connected ? undefined : 'ok', text: connected ? 'Verbindung wird getrennt' : 'Sichere Worker-Verbindung angefordert' }]); } catch (error) { setLogs((items) => [...items, { time: now(), tone: 'warn', text: error instanceof Error ? error.message : 'Worker nicht erreichbar' }]); } finally { setBusy(false); } }
  async function instanceAction(action: 'join' | 'disconnect' | 'restart') { if (busy) return; setBusy(true); try { await call(action); setStatus(action === 'disconnect' ? 'disconnecting' : 'connecting'); setLogs((items) => [...items, { time: now(), tone: action === 'disconnect' ? undefined : 'ok', text: action === 'join' ? 'Serverbeitritt gestartet' : action === 'restart' ? 'Instanz wird vollständig neu gestartet' : 'Verbindung wird getrennt' }]); } catch (error) { setLogs((items) => [...items, { time: now(), tone: 'warn', text: error instanceof Error ? error.message : 'Aktion fehlgeschlagen' }]); } finally { setBusy(false); } }
  async function sendCommand(event: FormEvent) { event.preventDefault(); if (!command.trim()) return; const message = command.trim(); const isJoinServer = /^\/joinserver\s+/i.test(message); if (status !== 'online' && !isJoinServer) { setLogs((items) => [...items, { time: now(), tone: 'warn', text: 'Offline ist nur /joinserver "serverip" verfügbar' }]); return; } try { await call('chat', { message }); setLogs((items) => [...items, { time: now(), tone: isJoinServer ? 'ok' : undefined, text: `> ${message}` }]); if (isJoinServer) setStatus('connecting'); setCommand(''); } catch (error) { setLogs((items) => [...items, { time: now(), tone: 'warn', text: error instanceof Error ? error.message : 'Senden fehlgeschlagen' }]); } }
  async function move(action: string) { try { await call('control', { action }); } catch (error) { setLogs((items) => [...items, { time: now(), tone: 'warn', text: error instanceof Error ? error.message : 'Steuerung fehlgeschlagen' }]); setView('console'); } }
  async function changeConnectionMode(mode: ConnectionMode) {
    if (busy || mode === connectionMode) return;
    setBusy(true);
    try {
      await call('connection-mode', { mode });
      setConnectionMode(mode);
      setLogs((items) => [...items, { time: now(), tone: 'ok', text: mode === 'proxy' ? 'SOCKS5-Modus aktiviert' : 'Railway-IP-Modus aktiviert · deine Heim-IP bleibt ungenutzt' }]);
    } catch (error) { setLogs((items) => [...items, { time: now(), tone: 'warn', text: error instanceof Error ? error.message : 'Verbindungsmodus konnte nicht geändert werden' }]); }
    finally { setBusy(false); }
  }

  async function copyDeviceCode() {
    if (!microsoftAuth) return;
    try { await navigator.clipboard.writeText(microsoftAuth.code); setLogs((items) => [...items, { time: now(), tone: 'ok', text: 'Microsoft-Gerätecode in die Zwischenablage kopiert' }]); }
    catch { setLogs((items) => [...items, { time: now(), tone: 'warn', text: 'Gerätecode konnte nicht kopiert werden' }]); }
  }

  return <main className="shell"><aside className="rail"><div className="brand-mark" aria-label="Remote Console Client (RCC)">R</div><nav aria-label="Hauptnavigation">
    <button className={`rail-button ${view === 'console' ? 'active' : ''}`} onClick={() => setView('console')} aria-label="Konsole">⌘</button>
    <button className={`rail-button ${view === 'world' ? 'active' : ''}`} onClick={() => setView('world')} aria-label="Live-Welt">▦</button>
    <button className={`rail-button ${view === 'account' ? 'active' : ''}`} onClick={() => setView('account')} aria-label="Microsoft-Session">◉</button>
    <button className={`rail-button ${view === 'security' ? 'active' : ''}`} onClick={() => setView('security')} aria-label="Sicherheit">◇</button>
  </nav><div className="avatar" aria-label="Sicher angemeldet">✓</div></aside>
  <section className="workspace"><header className="topbar"><div><p className="eyebrow">RCC / {heading.toUpperCase()}</p><h1>{view === 'world' ? 'Sieh, was dein Bot sieht.' : view === 'security' ? 'Deine Verbindung bleibt privat.' : view === 'account' ? 'Dein Microsoft-Login bleibt bei dir.' : 'Deine Welt bleibt online.'}</h1></div><div className="top-actions"><div className={`live-pill ${liveStream ? 'active' : ''}`}><span /> {liveStream ? 'LIVE · 250 MS' : 'VERBINDET'}</div><div className="login-pill">✓ Sicher angemeldet</div><div className={`safety-pill ${connectionMode === 'railway-direct' ? 'railway-mode' : ''}`}><span /> {connectionMode === 'proxy' ? 'SOCKS5-ONLY' : 'RAILWAY-IP'}</div></div></header>
  <div className="status-strip"><div className={`pulse ${status === 'online' ? 'live' : ''}`} /><div><strong>{status === 'online' ? 'Online' : status === 'connecting' ? 'Verbindet…' : status === 'disconnecting' ? 'Trennt…' : 'Bereit zum Start'}</strong><small>{status === 'online' ? 'Serverseitige Instanz läuft' : 'Worker läuft unabhängig von deinem Laptop'}</small></div><div className="status-metric"><small>Eigene IP</small><strong>Niemals genutzt</strong></div><button className={connected ? 'danger-button' : 'primary-button'} onClick={toggleConnection} disabled={busy}>{connected ? 'Verbindung trennen' : 'Sicher verbinden'}</button></div>
  <section className="quick-stats" aria-label="RCC Statusübersicht"><article><span className="stat-icon green">●</span><div><small>Client-Status</small><b>{status === 'online' ? 'Operational' : status === 'connecting' ? 'Connecting' : 'Standby'}</b></div></article><article><span className="stat-icon cyan">⌁</span><div><small>Verbindungsmodus</small><b>{connectionMode === 'proxy' ? 'SOCKS5 only' : 'Railway-Ausgangs-IP'}</b></div></article><article><span className="stat-icon purple">◉</span><div><small>Microsoft-Session</small><b>{microsoftAuth ? 'Bestätigung offen' : 'Serverseitig geschützt'}</b></div></article><article><span className="stat-icon orange">▦</span><div><small>Live-Viewer</small><b>{status === 'online' ? 'Bereit' : 'Wartet auf Join'}</b></div></article></section>
  <div className="instance-actions" aria-label="Instanz steuern"><button onClick={() => instanceAction('join')} disabled={busy || connected}><span>▶</span><strong>Server beitreten</strong><small>{connectionMode === 'proxy' ? 'SOCKS5 starten' : 'Railway-IP starten'}</small></button><button onClick={() => instanceAction('disconnect')} disabled={busy || !connected}><span>■</span><strong>Trennen</strong><small>Server verlassen</small></button><button onClick={() => instanceAction('restart')} disabled={busy}><span>↻</span><strong>Neu verbinden</strong><small>Client neu starten</small></button><button onClick={() => { setView('console'); window.setTimeout(() => document.querySelector<HTMLInputElement>('.commandbar input')?.focus(), 0); }}><span>›</span><strong>Command</strong><small>Konsole öffnen</small></button></div>

  {view === 'console' && <>{microsoftAuth && <section className="device-code-panel"><div><p className="eyebrow">MICROSOFT DEVICE LOGIN</p><h2>Einmalig bestätigen, dann bleibt die Sitzung im Worker.</h2><p>Öffne die offizielle Microsoft-Seite. Dein Passwort und dein Token gehen nie an RCC oder den Browser.</p></div><code>{microsoftAuth.code}</code><div className="device-code-actions"><a className="primary-button" href={microsoftAuth.url} target="_blank" rel="noreferrer">Microsoft öffnen</a><button className="secondary-button" type="button" onClick={copyDeviceCode}>Code kopieren</button></div></section>}<div className="content-grid"><section className="console-card"><div className="card-head"><div><p className="eyebrow">LIVE SESSION</p><h2>Konsole</h2></div><span className="latency">{status === 'online' ? 'LIVE' : '—'}</span></div><div className="terminal" role="log" aria-live="polite">{logs.map((entry, index) => <p key={`${entry.time}-${index}`} className={entry.tone}><time>{entry.time}</time><span>{entry.text}</span></p>)}{!connected && <div className="terminal-empty"><span>⌁</span><strong>Noch offline</strong><small>Starte mit /joinserver „serverip“ oder „Sicher verbinden“.</small></div>}</div><form className="commandbar" onSubmit={sendCommand}><span>›</span><input value={command} onChange={(event) => setCommand(event.target.value)} placeholder={status === 'online' ? 'Chat oder /command' : '/joinserver "serverip"'} aria-label="Chat oder Befehl" /><button disabled={!command.trim()}>Senden</button></form></section><ConfigCard connectionMode={connectionMode} railwayDirectAvailable={railwayDirectAvailable} busy={busy} onModeChange={changeConnectionMode} /></div></>}

  {view === 'world' && <div className="world-layout"><section className="world-card"><div className="card-head"><div><p className="eyebrow">{world ? 'ECHTE LIVE-WELT' : 'STARTMENÜ-VORSCHAU'}</p><h2>{world ? 'First-Person Viewer' : 'So sieht deine Session aus'}</h2></div><span className="latency">{world ? '3D · LIVE' : 'VORSCHAU'}</span></div>{world ? viewerUrl ? <iframe className="live-viewer" src={viewerUrl} title="Minecraft Live-Viewer" allow="fullscreen" /> : <><div className="world-map" aria-label="Draufsicht der Minecraft-Umgebung">{world.blocks.flatMap((row, z) => row.map((name, x) => <div key={`${x}-${z}`} className={`block ${blockKind(name)} ${x === 7 && z === 7 ? 'bot-block' : ''}`} title={name}>{x === 7 && z === 7 ? '▲' : ''}</div>))}</div><div className="world-legend"><span>Live-Viewer wird sicher geöffnet…</span></div></> : <div className="minecraft-preview" role="img" aria-label="Vorschau einer Minecraft-Landschaft"><div className="preview-sky"><span className="preview-sun" /><span className="preview-cloud cloud-one" /><span className="preview-cloud cloud-two" /></div><div className="preview-hills"><i /><i /><i /><i /></div><div className="preview-ground"><span className="preview-crosshair">+</span><div className="preview-hotbar"><b>▣</b><b>◇</b><b>▥</b><b>▦</b><b>◆</b><b>□</b><b>□</b><b>□</b><b>□</b></div></div><div className="preview-label"><strong>Offline-Vorschau</strong><span>Nach dem Beitritt erscheint hier die echte 3D-Welt.</span></div></div>}</section><aside className="telemetry-card"><p className="eyebrow">SPIELSTATUS</p><h2>Bot-Steuerung</h2><div className="stats"><div><span>Position</span><strong>{world ? `${world.position.x} / ${world.position.y} / ${world.position.z}` : '—'}</strong></div><div><span>Leben</span><strong>{world ? `${world.health} / 20` : '—'}</strong></div><div><span>Hunger</span><strong>{world ? `${world.food} / 20` : '—'}</strong></div><div><span>Dimension</span><strong>{world?.dimension ?? '—'}</strong></div></div><div className="movement" aria-label="Bot bewegen"><button onClick={() => move('forward')} disabled={!world}>W</button><button onClick={() => move('left')} disabled={!world}>A</button><button onClick={() => move('back')} disabled={!world}>S</button><button onClick={() => move('right')} disabled={!world}>D</button><button className="jump" onClick={() => move('jump')} disabled={!world}>Springen</button></div><div className="players"><span>Spieler online</span><strong>{world?.players.length ?? 0}</strong>{world?.players.length ? <p>{world.players.join(', ')}</p> : null}</div></aside></div>}

  {view === 'security' && <div className="security-grid"><section><span className="security-icon">◆</span><p className="eyebrow">VERBINDUNGSWEG</p><h2>{connectionMode === 'proxy' ? 'SOCKS5 erzwungen' : 'Railway-IP aktiv'}</h2><p>{connectionMode === 'proxy' ? 'Scheitert der SOCKS5-Tunnel, bleibt der Minecraft-Client offline. Es gibt keinen Direkt-Fallback.' : 'Der Worker verbindet direkt von Railways Server-Netzwerk. Deine Heim-IP wird dabei nicht verwendet.'}</p></section><section><span className="security-icon">●</span><p className="eyebrow">SECRETS</p><h2>Daten bleiben serverseitig</h2><p>Minecraft-, Proxy- und API-Zugangsdaten werden nicht an deinen Browser übertragen.</p></section><section><span className="security-icon">✓</span><p className="eyebrow">PRIVATE SITE</p><h2>Nur dein Login</h2><p>Das Dashboard bleibt durch die private Codex-Sites-Anmeldung geschützt.</p></section></div>}
  {view === 'account' && <section className="account-grid"><article className="account-main"><p className="eyebrow">MICROSOFT ACCOUNT</p><h2>Spielen ohne Token im Browser</h2><p>RCC verwendet die offizielle Geräteanmeldung von Microsoft. Nach der ersten Bestätigung liegt nur der Sitzungs-Cache im serverseitigen Worker — niemals als lesbarer Wert auf dieser Website.</p><div className="account-points"><span>✓ Microsoft-Passwort bleibt bei Microsoft</span><span>✓ Browser erhält keine Minecraft- oder Proxy-Zugangsdaten</span><span>✓ Mit Railway-Volume bleibt der Cache nach Neustarts erhalten</span></div>{microsoftAuth ? <div className="account-code"><span>Dein aktueller Gerätecode</span><code>{microsoftAuth.code}</code><a href={microsoftAuth.url} target="_blank" rel="noreferrer">Microsoft-Anmeldung öffnen →</a></div> : <div className="account-code muted-code"><span>Kein offener Gerätecode</span><strong>Beim nächsten „Sicher verbinden“ wird bei Bedarf ein offizieller Code angezeigt.</strong></div>}</article><aside className="account-side"><p className="eyebrow">SITZUNGSSTATUS</p><h2>Serverseitig</h2><dl><div><dt>Token-Eingabe</dt><dd>Nicht erforderlich</dd></div><div><dt>Cache-Speicher</dt><dd>Nur Worker</dd></div><div><dt>Verbindung</dt><dd>{connectionMode === 'proxy' ? 'SOCKS5' : 'Railway-IP'}</dd></div><div><dt>Client</dt><dd>{status === 'online' ? 'Online' : 'Offline'}</dd></div></dl><button className="secondary-button" type="button" onClick={() => setView('console')}>Zur Konsole</button></aside></section>}
  <footer><span>RCC</span><p>Remote Console Client · Mineflayer 26.1 · SOCKS5 oder Railway-IP · Live-Viewer</p><span>v1.1</span></footer></section></main>;
}

function ConfigCard({ connectionMode, railwayDirectAvailable, busy, onModeChange }: { connectionMode: ConnectionMode; railwayDirectAvailable: boolean; busy: boolean; onModeChange: (mode: ConnectionMode) => void }) { return <aside className="config-card"><div className="card-head"><div><p className="eyebrow">VERBINDUNG</p><h2>Instanz</h2></div><span className="lock">●</span></div><label>Server-Adresse<input value="Im Worker konfiguriert" disabled /></label><div className="split"><label>Port<input value="Worker" disabled /></label><label>Edition<select aria-label="Edition" defaultValue="java" disabled><option value="java">Java</option></select></label></div><label>Minecraft-Konto<input value="Microsoft-Geräteanmeldung" disabled /></label><div className="proxy-box"><div className="proxy-title"><span className="shield">◆</span><div><strong>{connectionMode === 'proxy' ? 'Proxy-Zwang aktiv' : 'Railway-IP-Modus aktiv'}</strong><small>{connectionMode === 'proxy' ? 'Kein automatischer Direkt-Fallback' : 'Keine Verbindung über deinen Laptop'}</small></div></div><div className="mode-switch" role="group" aria-label="Verbindungsmodus"><button type="button" className={connectionMode === 'proxy' ? 'selected' : ''} onClick={() => onModeChange('proxy')} disabled={busy}>SOCKS5</button><button type="button" className={connectionMode === 'railway-direct' ? 'selected' : ''} onClick={() => onModeChange('railway-direct')} disabled={busy || !railwayDirectAvailable} title={railwayDirectAvailable ? 'Direkt über Railways Server-IP verbinden' : 'In Railway zuerst ALLOW_RAILWAY_DIRECT_EGRESS=true setzen'}>Railway-IP</button></div><label>SOCKS5 Proxy<input value={connectionMode === 'proxy' ? 'Sicher im Worker hinterlegt' : 'Im Railway-IP-Modus nicht genutzt'} disabled /></label><div className="guard-row"><span>Heim-IP</span><strong>NIEMALS</strong></div></div><p className="privacy-note">Der Microsoft-Sitzungs-Cache bleibt ausschließlich im Railway-Worker. Mit einem Volume bleibt die Anmeldung auch nach einem Neustart erhalten.</p></aside>; }
